version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "workshopEventProducer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bq0iliuj762r"
s3_prefix = "workshopEventProducer"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

